# Generated by Django 4.0.1 on 2022-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_Details',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('app_start_time', models.DateTimeField()),
                ('app_submission_time', models.DateTimeField()),
                ('applicant_name', models.CharField(max_length=30)),
                ('app_email', models.CharField(max_length=40)),
                ('app_onphone', models.CharField(max_length=15)),
                ('app_ssn', models.CharField(max_length=15)),
                ('app_mailing', models.CharField(max_length=100)),
                ('renter', models.IntegerField(max_length=10)),
                ('unit_type', models.CharField(max_length=100)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin_ip', models.CharField(max_length=18)),
                ('classification', models.CharField(max_length=20)),
                ('AI_prediction', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
