# Generated by Django 4.0.1 on 2022-02-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_fraudulent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk_table',
            options={},
        ),
    ]
