# Generated by Django 4.0.1 on 2022-01-20 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ml_fraudulent_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_details',
            old_name='id',
            new_name='app_id',
        ),
        migrations.AddField(
            model_name='applicant_details',
            name='geoLocation',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='app_mailing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='app_start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 10, 32, 6, 768848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='app_submission_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 10, 32, 6, 768848, tzinfo=utc)),
        ),
    ]
