# Generated by Django 4.0.1 on 2022-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_fraudulent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_table',
            name='Risk_Score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
