# Generated by Django 4.0.1 on 2022-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_fraudulent_app', '0002_alter_risk_table_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='importance_rank_table',
            name='Count',
            field=models.IntegerField(default=0),
        ),
    ]
