# Generated by Django 4.0.1 on 2022-01-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_fraudulent_app', '0002_rename_id_applicant_details_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='app_start_time',
            field=models.DateTimeField(default='2022-01-20 16:08:21.927075'),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='app_submission_time',
            field=models.DateTimeField(default='2022-01-20 16:08:21.927075'),
        ),
    ]
