# Generated by Django 4.0.1 on 2022-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_fraudulent_app', '0003_importance_rank_table_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importance_rank_table',
            name='Importance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
